spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/imsdb
    username: root
    password: codename47SUNBRO@239485672
    driver-class-name: org.mariadb.jdbc.Driver

#isccrms-cors:
#  origin: ${CORS_ORIGIN}